In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [4]:
df = pd.read_csv("screentime.csv")

In [5]:
df.head()

,user_id,age,gender,occupation_type,chronotype,bedtime_phone_minutes,primary_bedtime_app,screen_brightness_pct,blue_light_filter_active,caffeine_post_5pm_mg,physical_activity_min,sleep_latency_min,total_sleep_hours,deep_sleep_pct,rem_sleep_pct,morning_alarm_snoozes,next_day_fatigue_score,sleep_debt_category
0,USR-00001,29,Female,Healthcare / Shift Worker,Intermediate,179,Instagram / Reddit,54,1,0,21,84.4,3.20,23.5,22.2,7,10.0,Severe Sleep Debt
1,USR-00002,58,Female,Student,Intermediate,163,YouTube,76,1,92,72,86.7,4.06,18.0,21.5,7,10.0,Severe Sleep Debt
2,USR-00003,41,Female,Healthcare / Shift Worker,Night Owl,100,TikTok / Reels,59,0,45,23,70.5,3.20,18.1,20.5,7,10.0,Severe Sleep Debt
3,USR-00004,36,Non-Binary,Remote Tech,Intermediate,34,YouTube,52,0,97,49,38.1,6.99,21.6,22.4,1,1.7,Mild Deficit
4,USR-00005,23,Female,Healthcare / Shift Worker,Intermediate,27,TikTok / Reels,82,1,0,38,32.3,4.58,24.1,22.8,4,5.3,Moderate Debt

In [6]:
df.tail()

,user_id,age,gender,occupation_type,chronotype,bedtime_phone_minutes,primary_bedtime_app,screen_brightness_pct,blue_light_filter_active,caffeine_post_5pm_mg,physical_activity_min,sleep_latency_min,total_sleep_hours,deep_sleep_pct,rem_sleep_pct,morning_alarm_snoozes,next_day_fatigue_score,sleep_debt_category
8495,USR-08496,61,Female,Remote Tech,Night Owl,18,Streaming (Netflix/Hulu),61,1,60,74,21.0,5.57,26.5,18.1,3,3.2,Moderate Debt
8496,USR-08497,64,Male,Student,Night Owl,138,TikTok / Reels,58,1,0,58,84.3,3.99,20.4,19.4,7,10.0,Severe Sleep Debt
8497,USR-08498,34,Male,Corporate 9-to-5,Intermediate,56,Streaming (Netflix/Hulu),56,0,94,33,40.6,7.58,17.4,20.7,2,3.7,Mild Deficit
8498,USR-08499,23,Male,Healthcare / Shift Worker,Night Owl,165,TikTok / Reels,72,0,0,52,123.3,3.20,14.2,15.8,7,10.0,Severe Sleep Debt
8499,USR-08500,27,Female,Student,Night Owl,108,Instagram / Reddit,35,1,0,23,55.7,4.04,27.3,18.7,5,6.7,Moderate Debt

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8500 entries, 0 to 8499
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   user_id                   8500 non-null   object
 1   age                       8500 non-null   int64
 2   gender                    8500 non-null   object
 3   occupation_type           8500 non-null   object
 4   chronotype                8500 non-null   object
 5   bedtime_phone_minutes     8500 non-null   int64
 6   primary_bedtime_app       8500 non-null   object
 7   screen_brightness_pct     8500 non-null   int64
 8   blue_light_filter_active  8500 non-null   int64
 9   caffeine_post_5pm_mg      8500 non-null   int64
 10  physical_activity_min     8500 non-null   int64
 11  sleep_latency_min         8500 non-null   float64
 12  total_sleep_hours         8500 non-null   float64
 13  deep_sleep_pct            8500 non-null   float64
 14  rem_sleep_pct             8500 non-null   float64
 15  morning_alarm_snoozes     8500 non-null   int64
 16  next_day_fatigue_score    8500 non-null   float64
 17  sleep_debt_category       8500 non-null   object
dtypes: float64(5), int64(7), object(6)
memory usage: 1.2+ MB

In [8]:
df.describe()

,age,bedtime_phone_minutes,screen_brightness_pct,blue_light_filter_active,caffeine_post_5pm_mg,physical_activity_min,sleep_latency_min,total_sleep_hours,deep_sleep_pct,rem_sleep_pct,morning_alarm_snoozes,next_day_fatigue_score
count,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000
mean,34.355647,59.250000,55.153882,0.467765,33.222471,35.701412,40.671471,6.266209,21.735741,19.105859,2.766000,3.794671
std,11.584259,36.931991,19.850550,0.498989,51.935645,20.819390,17.444914,1.446258,3.069377,2.546459,1.695407,2.685153
min,18.000000,1.000000,10.000000,0.000000,0.000000,0.000000,6.000000,3.200000,8.100000,9.600000,0.000000,1.000000
25%,25.000000,31.000000,42.000000,0.000000,0.000000,21.000000,28.200000,5.240000,19.700000,17.400000,2.000000,1.100000
50%,32.000000,51.000000,55.000000,0.000000,0.000000,35.000000,37.600000,6.330000,21.900000,19.100000,3.000000,3.200000
75%,42.000000,79.000000,69.000000,1.000000,55.000000,50.000000,49.700000,7.350000,23.900000,20.800000,4.000000,5.600000
max,65.000000,180.000000,100.000000,1.000000,250.000000,112.000000,123.300000,9.800000,28.000000,27.000000,7.000000,10.000000

In [9]:
df.shape

(8500, 18)

In [10]:
dfn = df.drop("user_id",axis=1)

In [11]:
dfn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8500 entries, 0 to 8499
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       8500 non-null   int64
 1   gender                    8500 non-null   object
 2   occupation_type           8500 non-null   object
 3   chronotype                8500 non-null   object
 4   bedtime_phone_minutes     8500 non-null   int64
 5   primary_bedtime_app       8500 non-null   object
 6   screen_brightness_pct     8500 non-null   int64
 7   blue_light_filter_active  8500 non-null   int64
 8   caffeine_post_5pm_mg      8500 non-null   int64
 9   physical_activity_min     8500 non-null   int64
 10  sleep_latency_min         8500 non-null   float64
 11  total_sleep_hours         8500 non-null   float64
 12  deep_sleep_pct            8500 non-null   float64
 13  rem_sleep_pct             8500 non-null   float64
 14  morning_alarm_snoozes     8500 non-null   int64
 15  next_day_fatigue_score    8500 non-null   float64
 16  sleep_debt_category       8500 non-null   object
dtypes: float64(5), int64(7), object(5)
memory usage: 1.1+ MB

In [12]:
target = {"Optimal Recovery":1,"Mild Deficit":2,"Moderate Debt":3,"Severe Sleep Debt":4}

In [13]:
dfn["Target values"] = dfn["sleep_debt_category"].map(target)

In [14]:
dfn2 = dfn.drop("sleep_debt_category",axis=1)

In [15]:
dfn3 = pd.get_dummies(dfn2,dtype = int)

In [16]:
x = dfn3.drop("Target values",axis=1)
y = dfn3["Target values"]

In [17]:
x.shape

(8500, 29)

In [18]:
y.shape

(8500,)

In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [20]:
Logistic = LogisticRegression()
Logistic.fit(x_train,y_train)

/Users/shaikhruhan923gmail.com/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_linear_loss.py:203: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights.T + intercept  # ndarray, likely C-contiguous
/Users/shaikhruhan923gmail.com/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_linear_loss.py:203: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights.T + intercept  # ndarray, likely C-contiguous
/Users/shaikhruhan923gmail.com/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_linear_loss.py:203: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights.T + intercept  # ndarray, likely C-contiguous
/Users/shaikhruhan923gmail.com/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_linear_loss.py:336: RuntimeWarning: divide by zero encountered in matmul
  grad[:, :n_features] = grad_pointwise.T @ X + l2_reg_strength * weights
/Users/shaikhruhan923gmail.com/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_linear_loss.py:336: RuntimeWarning: overflow encountered in matmul
  grad[:, :n_features] = grad_pointwise.T @ X + l2_reg_strength * weights
/Users/shaikhruhan923gmail.com/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_linear_loss.py:336: RuntimeWarning: invalid value encountered in matmul
  grad[:, :n_features] = grad_pointwise.T @ X + l2_reg_strength * weights
/Users/shaikhruhan923gmail.com/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [21]:
y_pred = Logistic.predict(x_test)

/Users/shaikhruhan923gmail.com/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/shaikhruhan923gmail.com/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/shaikhruhan923gmail.com/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b

In [22]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
accuracy_score(y_pred,y_test)

0.8476470588235294

In [23]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           1       0.78      0.82      0.80       265
           2       0.76      0.70      0.73       404
           3       0.91      0.92      0.92       902
           4       0.78      0.88      0.83       129

    accuracy                           0.85      1700
   macro avg       0.81      0.83      0.82      1700
weighted avg       0.85      0.85      0.85      1700

In [24]:
print(confusion_matrix(y_pred,y_test))

[[218  45   2   0]
 [ 61 284  59   0]
 [  0  45 826  31]
 [  0   0  16 113]]

In [25]:
from sklearn.tree import DecisionTreeClassifier

In [26]:
CT = DecisionTreeClassifier()
CT.fit(x_train,y_train)
CT_PRED = CT.predict(x_test)

In [27]:
print(classification_report(y_test,CT_PRED))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00       279
           2       1.00      1.00      1.00       374
           3       1.00      1.00      1.00       903
           4       1.00      1.00      1.00       144

    accuracy                           1.00      1700
   macro avg       1.00      1.00      1.00      1700
weighted avg       1.00      1.00      1.00      1700

In [28]:
print(confusion_matrix(y_test,CT_PRED))

[[279   0   0   0]
 [  0 374   0   0]
 [  0   0 903   0]
 [  0   0   0 144]]